config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :blogs, only: [:index, :show]

  resources :categories
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :blogs, except: [:index, :show]
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def index
    @blogs = Blog.all
    @users = User.all
    @categories = Category.all
  end

  private

  def require_admin
    unless current_user.admin?
      flash[:alert] = "You are not authorized to access this section."
      redirect_to root_path
    end
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/_admin_sidebar.html.erb
<button class="btn btn-info mt-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"><i class="fa fa-sharp fa-regular fa-arrow-right "></i> </button>
<div class="offcanvas offcanvas-start w-auto" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Backdrop with scrolling</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  
  <div class="d-flex flex-column flex-shrink-0 p-3" style="width: 280px;">
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <i class="fa fa-sharp fa-regular fa-home me-2 "></i> 
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <i class="fa fa-sharp fa-regular fa-dashboard me-2 "></i> 
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <i class="fa fa-sharp fa-regular fa-book me-2 "></i>    
          Blogs
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <i class="fa fa-sharp fa-regular fa-user me-2 "></i>   
          Users
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/admin/dashboard/index.html.erb
<%= render 'admin_sidebar' %>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card  text-center">
        <%=image_tag 'users1.png', class:"card-img-top",style: "height:260px;"%>
        <div class="card-body">
        <h5 class="card-title">Total Users: <%= @users.count%></h5>
        <%= link_to 'Show', "", class:"btn btn-primary w-100"%>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card text-center">
        <%=image_tag 'blogs.png', class:"card-img-top" ,style: "height:260px;"%>  
        <div class="card-body">
        <h5 class="card-title">Total Blogs: <%= @blogs.all.count%></h5>
        <%= link_to 'Show', "", class:"btn btn-primary w-100"%>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card text-center">
        <%=image_tag 'category.png', class:"card-img-top",style: "height:260px;"%>
        <div class="card-body">
        <h5 class="card-title">Total Categories: <%= @categories.all.count%></h5>
        <%= link_to 'Show', "", class:"btn btn-primary w-100"%>
        </div>
      </div>
    </div>
  </div>

  <%# Table %>
  <table class="table caption-top">
    <caption>List of Blogs</caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Blog Headline</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @blogs.each_with_index do |blog, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= blog.headline %></td>
          <td>
            <%= link_to blog_path(blog), class: "btn btn-primary" do %>
              <i class="fa fa-eye"></i>
            <% end %>
            <%= link_to edit_admin_blog_path(blog), class: "btn btn-warning" do %>
              <i class="fa fa-pencil"></i>
            <% end %>
            <%= link_to admin_blog_path(blog), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },  class: "btn btn-danger" do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>