config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :blogs, only: [:index, :show]

  resources :categories
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :blogs, except: [:index, :show]
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :description, :category_ids, presence: true
  validates :headline, presence: true, uniqueness: { case_sensitive: true }
  has_rich_text :description
  has_one_attached :image
  has_many :blog_categories,dependent: :destroy
  has_many :categories, through: :blog_categories
  before_validation :generate_slug
  validates :slug, uniqueness: true, presence: true

  def to_param
    slug
  end

  private

  def generate_slug
    self.slug ||= headline.parameterize
  end

end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :set_blog, only: [:edit,:update,:destroy]
  before_action :set_categories, only: [:new,:create, :edit, :update]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to @blog, notice: "blog created successfully!"
    else
      flash[:alert] = "Failed to create a blog."
      redirect_to new_admin_blog_path
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog), notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to admin_dashboard_path, notice: 'Blog was successfully destroyed.'
  end

  private

  def blog_params
    params.require(:blog).permit(:headline, :description, :slug, :image, category_ids: [])
  end

  def set_blog
    @blog = Blog.find_by!(slug: params[:id])
  end

  def set_categories
    @categories =  Category.all
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show]

  def index
    if params[:category]
      @blogs = Blog.joins(:categories).where(categories: { name: params[:category] })
    else
      @blogs = Blog.all
    end
  end

  def show
  end

  private

  def blog_params
    params.require(:blog).permit(:headline, :description, :slug, :image, category_ids: [])
  end

  def set_blog
    @blog = Blog.find_by!(slug: params[:id])
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/admin/blogs/edit.html.erb
<div class="container">
  <h1>Update Blog</h1>

  <%= form_with(model: @blog, url: admin_blog_path) do |form| %>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.label :categories %><br>
      <%= form.collection_check_boxes :category_ids, @categories, :id, :name %>
    </div>

    <div class="field">
      <%= form.label :headline %>
      <%= form.text_field :headline %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.rich_text_area :description , placeholder:"Write blog"%>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/admin/blogs/new.html.erb
<div class="container">
  <h1>New Blog</h1>

  <%= form_with(model: @blog, url: admin_blogs_path) do |form| %>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.label :categories %><br>
      <%= form.collection_check_boxes :category_ids, @categories, :id, :name %>
    </div>

    <div class="field">
      <%= form.label :headline %>
      <%= form.text_field :headline %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.rich_text_area :description , placeholder:"Write blog"%>
      
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

  <%= link_to 'Back', blogs_path %>
</div>